feat: add booking and comment feature
lliauh/java-shareit pull request #2
Opened 2024-05-20 06:24 UTC by lliauh

2024-05-20 13:58 UTC, ErkinKasymaliev requested changes
привет, оставил комменты

2024-05-20 13:58 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        checkIfBookingIsValid(booking);
это поставьте сразу после `Booking booking = bookingMapper.toBooking(bookingDto);`

2024-05-20 13:58 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        if (approved) {
```
BookingStatus status = approved ? BookingStatus.APPROVED : BookingStatus.REJECTED;
booking.setStatus(status);
```

2024-05-20 13:58 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        boolean isBooker = bookingRepository.getReferenceById(bookingId).getBooker().getId().equals(userId);
зачем вы вызываете bookingRepository.getReferenceById(bookingId) 2 раза. Вызовите 1 раз и запищите в переменную и работайте дальше с ней

2024-05-20 13:58 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +    public List<BookingOutDto> getBookingsOnUserItemsByState(@RequestParam(defaultValue = "ALL") String state,
state в enum

2024-05-20 13:58 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +    public List<BookingOutDto> getUserBookingsByState(@RequestParam(defaultValue = "ALL") String state,
state в enum

2024-05-20 13:58 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
>          if (item.getName() == null) {
что то мне эта логика не нравится. Лучше так:
```
Item item = ItemMapper.toItem(itemDto);
Item currentItem = itemRepository.getReferenceById(itemId);
if (item.getName() I= null) {
 currentItem.setName(item.getName());
}
...
```

2024-05-20 13:58 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/user/UserServiceImpl.java
> -            user.setEmail(userRepository.getUserById(userId).getEmail());
смотрите коммент в ItemServiceImpl

2024-05-21 04:54 UTC, ErkinKasymaliev requested changes
привет, еще комменты оставил

2024-05-21 04:54 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        if (editedItem.getName() == null) {
тут должно быть !=, значит был в dto передано name, значит надо обновить. и везде так должно быть

2024-05-21 04:54 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +        for (BookingSearchState enumState : BookingSearchState.values()) {
вот это уберите в сам BookingSearchState как статик метод

2024-05-21 06:22 UTC, lliauh commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        if (editedItem.getName() == null) {
Добрый день! не совсем пониманию, у меня dto лежит в уже конвертированное в айтем - editedItem.
Именно его (editedItem) я передаю на сохранение в репозиторий.

И в этом месте я проверяю, пришло ли в dto обновленное имя:
- если пришло - оно и останется и будет передано на сохранение
- если не пришло (null), то в него положим имя из текущего объекта (currentItem)

2024-05-21 06:29 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        if (editedItem.getName() == null) {
ааа, ок, понял вас

2024-05-21 09:45 UTC, ErkinKasymaliev approved these changes
работа принята

2024-05-21 10:09 UTC, merged