feat: split app into 2 modules and add docker
lliauh/java-shareit pull request #4
Opened 2024-06-03 21:36 UTC by lliauh

2024-06-05 06:59 UTC, ErkinKasymaliev requested changes
привет, надо полностью убрать валидацию с контроллеров, dto и все что с ней связано из server

2024-06-05 06:59 UTC, ErkinKasymaliev commented on server/pom.xml
> +        <dependency>
этой зависимости здесь быть не должно

2024-06-05 06:59 UTC, ErkinKasymaliev commented on server/src/main/java/ru/practicum/shareit/booking/dto/BookingDto.java
> +    @NotNull
это тоже надо убрать

2024-06-05 06:59 UTC, ErkinKasymaliev commented on server/src/main/java/ru/practicum/shareit/exception/ValidationException.java
> +public class ValidationException extends RuntimeException {
это тоже надо убрать

2024-06-05 11:15 UTC, lliauh commented on server/pom.xml
> +        <dependency>
Привет!
верно же понимаю, что 
<dependency>
            <groupId>org.mockito</groupId>
            <artifactId>mockito-junit-jupiter</artifactId>
            <version>5.11.0</version>
            <scope>test</scope>
        </dependency>
        
        надо вынести в pom на уровень всего приложения, чтобы применялось ко всем модулям?

2024-06-05 11:28 UTC, lliauh commented on server/src/main/java/ru/practicum/shareit/exception/ValidationException.java
> +public class ValidationException extends RuntimeException {
у меня на сервере есть валидация букинга перед сохранением - это делается в сервисе

`if (booking.getStart().isBefore(LocalDateTime.now())) {
            throw new ValidationException("Start date of the booking can't be in the past");
        }

        if (!booking.getEnd().isAfter(booking.getStart())) {
            throw new ValidationException("End date of the booking should be after start date");
        }`

верно понимаю, что тут правильно унести эту валидацию в шлюз и на уровне контроллера сразу разворачивать невалидный букинг?

2024-06-05 13:03 UTC, ErkinKasymaliev commented on server/pom.xml
> +        <dependency>
нет, надо убрать
```
<groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-validation</artifactId>
            <version>2.3.1.RELEASE</version>
```

2024-06-05 13:03 UTC, ErkinKasymaliev commented on server/src/main/java/ru/practicum/shareit/exception/ValidationException.java
> +public class ValidationException extends RuntimeException {
ааа понял, если вам надо валидировать с данными, которые в бд, то оставляйте это исключение

2024-06-05 13:03 UTC, ErkinKasymaliev commented on server/src/main/java/ru/practicum/shareit/exception/ValidationException.java
> +public class ValidationException extends RuntimeException {
грубо говоря, вся валидация входных данных должна быть на шлюзе

2024-06-06 11:14 UTC, ErkinKasymaliev approved these changes
привте, работа принята

2024-06-06 11:24 UTC, merged